import type { Metadata } from "next";
import ToastProvider from "./ToastProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
      // className={inter.className}
      >
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
